global using MailKit;
global using MailKit.Net.Smtp;
global using MailKit.Security;
global using Microsoft.Extensions.DependencyInjection;
global using MimeKit;
global using Polly;
global using Polly.Retry;
global using System.Net.Sockets;
global using Xunit;
